name: wishkit
description: WishKit Flutter SDK - Collect user feedback and feature requests in your app.
version: 1.0.0
homepage: https://github.com/wishkit/wishkit-flutter
repository: https://github.com/wishkit/wishkit-flutter
issue_tracker: https://github.com/wishkit/wishkit-flutter/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0
  provider: ^6.1.0
  uuid: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
